# Generated by Django 4.2.2 on 2024-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='name')),
                ('last_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('is_activ', models.BooleanField(default=False, verbose_name='activ')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tema')),
                ('message', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('send_count', models.PositiveIntegerField(default=0, verbose_name='send_count')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='error_count')),
                ('last_send_at', models.DateTimeField(null=True, verbose_name='last_send_at')),
                ('clients', models.ManyToManyField(related_name='mailings', to='emailservice.client', verbose_name='clients')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
