# Generated by Django 4.2.2 on 2024-07-21 11:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0003_alter_mailing_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='send_count',
        ),
        migrations.AddField(
            model_name='mailing',
            name='period_mail',
            field=models.CharField(choices=[('ежедневно', 'Раз в день'), ('раз в неделю', 'Раз в неделю'), ('раз в месяц', 'Раз в месяц')], default='ежедневно', max_length=100, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_mail',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status_mail',
            field=models.CharField(choices=[('завершена', 'Завершена'), ('создана', 'Создана'), ('запущена', 'Запущена')], default='создана', max_length=100, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 11, 52, 44, 438535, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(related_name='mailings', to='emailservice.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='last_send_at',
            field=models.DateTimeField(null=True, verbose_name='Последняя рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тема рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменена'),
        ),
    ]
