# Generated by Django 4.2.2 on 2024-07-21 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0004_remove_mailing_error_count_remove_mailing_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 11, 56, 45, 295794, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
