# Generated by Django 4.2.2 on 2024-07-21 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0006_alter_mailing_stop_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 12, 21, 21, 244820, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
