# Generated by Django 4.2.2 on 2024-07-21 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0007_alter_mailing_stop_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_activ',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 13, 1, 41, 204417, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
