# Generated by Django 4.2.2 on 2024-07-21 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0009_alter_mailing_stop_mail_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующей отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 16, 23, 25, 420199, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
