# Generated by Django 4.2.2 on 2024-07-21 17:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0010_mailing_next_send_time_alter_mailing_stop_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_mail',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 17, 16, 23, 948322, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
