# Generated by Django 4.2.2 on 2024-07-21 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0011_alter_mailing_start_mail_alter_mailing_stop_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 18, 26, 11, 589185, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
