# Generated by Django 4.2.2 on 2024-07-22 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0012_alter_mailing_stop_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 20, 59, 40, 316522, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
