# Generated by Django 4.2.2 on 2024-07-30 20:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailservice', '0014_alter_log_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 20, 34, 42, 98399, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
