# Generated by Django 4.2.2 on 2024-07-30 20:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailservice', '0015_alter_client_company_alter_mailing_stop_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 20, 57, 17, 22423, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
