# Generated by Django 4.2.2 on 2024-08-06 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0016_remove_client_company_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 19, 17, 14, 893027, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
